baseURL = "https://example.pages.dev/"
languageCode = "en-us"
theme = "ananke"
title = "Some new title"
enableRobotsTXT = true
disableKinds = ["taxonomy"]

[pagination]
  pagerSize = 10

[params]
  description = "A minimal Hugo site for Cloudflare Pages."
